apiVersion: v1
kind: Secret

metadata:
  name: api-secret

type: Opaque

stringData:
  DATABASE_URL: "postgres://postgres:mynew@host.docker.internal:5432/urlshortener?sslmode=disable"
  JWT_SECRET: "your-super-secret-key-at-least-32-chars-long"